#!/bin/sh
# Attach to the current running docker container

PROGRAM=/bin/bash

if [[ -z "$1" ]]; then
    echo "$0 <containerID|name> [program]"
    exit
fi

if [[ -n "$2" ]]; then
    PROGRAM="$2"
fi

docker exec -it $1 $PROGRAM 
